### ISSUE TITLE
intertemporal budget constraint and discrete (labor) decisions

### ISSUE THREAD

**Issue by fexler** [fediskhakov/egdst#3]
Hi Fedor,

I have a problem regarding the timing in the budget constraint. I want to set up a model of stochastic labor income, where the individual can decide on the amount of labor supply AFTER learning the realization of the wage shock. As I understand the code and your paper, money@hand next period depends on savings this period and the discrete decision THIS period.

Can I set up the budget constraint or discrete decision in a way, that the individual decides on optimal labor supply tomorrow given the shock tomorrow? 

Thanks a lot.

**Comment by fediskhakov** [comment]
Florian, this is answered in our email correspondence, I believe.  Just copying the relevant part here for the record:
The issue you raise is not specific to EGM, it is specific to the model, whatever method you use to solve it.  With the labour supply model it's just a trick we use to avoid the need for another state variable, this is my understanding at least. We accept the assumption that the labour supply decisions are made before the realization of the shock to productivity or wage, and thus the shocks do not have to enter the state space (which is by definition the information used to base the choice on), instead they are idiosyncratic and can be integrated our in the Bellman equation. This would not to be the case if we want to model serial correlation or allow the decision maker to learn the shock before making the choice.
